In [1]:
import pandas as pd
import inflection

df_raw = pd.read_csv("dataset/zomato.csv")
df_raw.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,Botswana Pula(P),1,0,0,0,3,4.6,3F7E00,Excellent,619
1,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,Botswana Pula(P),1,0,0,0,3,4.6,3F7E00,Excellent,619
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,"European, Asian",...,Botswana Pula(P),0,0,0,0,4,4.7,3F7E00,Excellent,469
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,"Filipino, American, Italian, Bakery",...,Botswana Pula(P),0,0,0,0,3,4.4,5BA829,Very Good,867
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,Botswana Pula(P),0,0,0,0,3,4.4,5BA829,Very Good,858

# Limpeza do dataframe

In [20]:
# Fazendo uma cópia do dataset
df = df_raw.copy()

# Removendo espaços dos nomes das colunas
df.columns = df.columns.str.replace(' ', '_')

# Removendo colunas que não serão utilizadas
df.drop(["Switch_to_order_menu"], axis=1, inplace=True)

#Removendo valores "NaN" de todas as colunas
df.dropna(inplace=True)

df.drop(df[(df["Cuisines"] == "Drinks Only")].index)

df.drop(df[(df["Cuisines"] == "Mineira")].index)

,Restaurant_ID,Restaurant_Name,Country_Code,City,Address,Locality,Locality_Verbose,Longitude,Latitude,Cuisines,Average_Cost_for_two,Currency,Has_Table_booking,Has_Online_delivery,Is_delivering_now,Price_range,Aggregate_rating,Rating_color,Rating_text,Votes
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,1100,Botswana Pula(P),1,0,0,3,4.6,3F7E00,Excellent,619
1,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,1100,Botswana Pula(P),1,0,0,3,4.6,3F7E00,Excellent,619
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,"European, Asian",3100,Botswana Pula(P),0,0,0,4,4.7,3F7E00,Excellent,469
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,"Filipino, American, Italian, Bakery",800,Botswana Pula(P),0,0,0,3,4.4,5BA829,Very Good,867
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,700,Botswana Pula(P),0,0,0,3,4.4,5BA829,Very Good,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7522,5912546,Eataly,208,İstanbul,"Zorlu Center AVM, Köprü Katı, Levazım Mahalles...","Zorlu Center AVM, Levazım, Beşiktaş","Zorlu Center AVM, Levazım, Beşiktaş, İstanbul",29.017326,41.065322,"Italian, Pizza, Fresh Fish",300,Turkish Lira(TL),0,0,0,4,4.3,5BA829,Very Good,1367
7523,5913006,Tarihi Çınaraltı Aile Çay Bahçesi,208,İstanbul,"Çengelköy Mahallesi, Çınaraltı Camii Sokak, No...",Çengelköy Merkez,"Çengelköy Merkez, İstanbul",29.052620,41.050280,"Fast Food, Izgara, Seafood, Tea, Coffee",45,Turkish Lira(TL),0,0,0,2,4.5,3F7E00,Excellent,1172
7524,5923535,Boon Cafe & Restaurant,208,İstanbul,"Çengelköy Mahallesi, Çengelköy Caddesi, Kara S...",Çengelköy Merkez,"Çengelköy Merkez, İstanbul",29.052623,41.050717,Restaurant Cafe,140,Turkish Lira(TL),0,0,0,4,4.2,5BA829,Very Good,1160
7525,5914190,Kanaat Lokantası,208,İstanbul,"Sultantepe Mahallesi, Selmani Pak Caddesi, No ...",Üsküdar Merkez,"Üsküdar Merkez, İstanbul",29.016590,41.025741,"Home-made, Izgara",95,Turkish Lira(TL),0,0,0,3,4.0,5BA829,Very Good,770
7526,5913508,Katibim,208,İstanbul,"Mimar Sinan Mahallesi, Harem Sahilyolu, No 53,...",Üsküdar Merkez,"Üsküdar Merkez, İstanbul",29.010808,41.025501,"Restaurant Cafe, Kebab, Turkish Pizza",150,Turkish Lira(TL),0,0,0,4,4.2,5BA829,Very Good,1141

## Renomear as colunas do DataFrame

In [21]:
def rename_columns(dataframe):
    df = dataframe.copy()
    title = lambda x: inflection.titleize(x)
    snakecase = lambda x: inflection.underscore(x)
    spaces = lambda x: x.replace(" ", "")
    cols_old = list(df.columns)
    cols_old = list(map(title, cols_old))
    cols_old = list(map(spaces, cols_old))
    cols_new = list(map(snakecase, cols_old))
    df.columns = cols_new
    return df

df = rename_columns(df)

## Categorizando todos os restaurantes somente por um topo de culinária

In [22]:
df["cuisines"] = df["cuisines"].apply(lambda x: str(x).split(",")[0] if pd.notnull(x) else x)

In [23]:
#Remover valores "NaN" da coluna "Cuisines"
df = df[df["cuisines"].notnull()]

# Preenchimento do nome dos países

In [24]:
COUNTRIES = {
    1: "India",
    14: "Australia",
    30: "Brazil",
    37: "Canada",
    94: "Indonesia",
    148: "New Zealand",
    162: "Phillipines",
    166: "Qatar",
    184: "Singapore",
    189: "South Africa",
    191: "Sri Lanka",
    208: "Turkey",
    214: "United Arab Emirates",
    215: "United Kingdom",
    216: "United States"
}

def country_name(country_id):
    return COUNTRIES[country_id]

# Criando a coluna country na posição 2 do dataframe

In [25]:
#criando coluna Country na posição 2
df.insert(loc=2, column="country", value=df["country_code"].apply(country_name))

# Removendo a coluna country_code

In [26]:
#Removendo coluna Country_Code
df.drop(["country_code"], axis=1, inplace=True)

# Criação do tipo de categoria de comida

In [27]:
def create_price_type(price_range):
    if price_range == "1":
        return "cheap"
    elif price_range == "2":
        return "normal"
    elif price_range == "3":
        return "expensive"
    else:
        return "gourmet"

## Criando coluna price_type ao lado da coluna cuisines

In [28]:
df.insert(loc=10, column="price_type", value=df["price_range"].apply(create_price_type))

## Removendo a coluna price_range

In [29]:
#removendo coluna Price_Range
df.drop(["price_range"], axis=1, inplace=True)

# Criação do nome das cores

In [30]:
COLORS = {
    "3F7E00": "dark_green",
    "5BA829": "green",
    "9ACD32": "lightgreen",
    "CDD614": "orange",
    "FFBA00": "red",
    "CBCBC8": "darkred",
    "FF7800": "lightred",
}

def color_name(color_code):
    return COLORS[color_code]

## Criando a coluna color_name na posição 18

In [31]:
df.insert(loc=18, column="color_name", value=df["rating_color"].apply(color_name))

# Respondendo as perguntas de negócio

In [32]:
df1 = df.copy()

In [33]:
df1.head()

,restaurant,restaurant_name,country,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,aggregate_rating,rating_color,color_name,rating_text,votes
0,6310675,Mama Lou's Italian Kitchen,Phillipines,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,1100,Botswana Pula(P),1,0,0,4.6,3F7E00,dark_green,Excellent,619
1,6310675,Mama Lou's Italian Kitchen,Phillipines,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,1100,Botswana Pula(P),1,0,0,4.6,3F7E00,dark_green,Excellent,619
2,6314542,Blackbird,Phillipines,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,European,...,3100,Botswana Pula(P),0,0,0,4.7,3F7E00,dark_green,Excellent,469
3,6301293,Banapple,Phillipines,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,Filipino,...,800,Botswana Pula(P),0,0,0,4.4,5BA829,green,Very Good,867
4,6315689,Bad Bird,Phillipines,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,700,Botswana Pula(P),0,0,0,4.4,5BA829,green,Very Good,858

In [34]:
df1.dtypes

restaurant                int64
restaurant_name          object
country                  object
city                     object
address                  object
locality                 object
locality_verbose         object
longitude               float64
latitude                float64
cuisines                 object
price_type               object
average_cost_for_two      int64
currency                 object
has_table_booking         int64
has_online_delivery       int64
is_delivering_now         int64
aggregate_rating        float64
rating_color             object
color_name               object
rating_text              object
votes                     int64
dtype: object

# Geral

## 1. Quantos restaurantes únicos estão registrados?

In [32]:
df1["restaurant"].nunique()

6929

## 2. Quantos países únicos estão registrados?

In [106]:
df1["country"].nunique()

15

## 3. Quantas cidades únicas estão registradas?

In [107]:
df1["city"].nunique()

125

## 4. Qual o total de avaliações feitas?

In [58]:
df1["votes"].sum()

4194533

## 5. Qual o total de tipos de culinárias registradas?

In [109]:
df1["cuisines"].nunique()

165

# País

## 1. Qual o nome do país que possui mais cidades registradas?

In [110]:
# Nome do país que possui mais cidades registradas
df1.groupby("country")["city"].nunique().sort_values(ascending=False).head(1)

country
India    49
Name: city, dtype: int64

## 2. Qual o nome do país que possui mais restaurantes registrados?

In [111]:
df1.groupby("country")["restaurant"].nunique().sort_values(ascending=False).head(1)

country
India    3111
Name: restaurant, dtype: int64

## 3. Qual o nome do país que possui mais restaurantes com o nível de preço igual a 4 registrados?

In [112]:
df1[df1["price_range"] == 4]["country"].value_counts().idxmax()

'United States'

## 4. Qual o nome do país que possui a maior quantidade de tipos de culinárias distintos?

In [113]:
df1.groupby("country")["cuisines"].nunique().idxmax()

'India'

## 5. Qual o nome do país que possui a maior quantidade de avaliações feitas?

In [114]:
df1.groupby("country")["votes"].sum().sort_values(ascending=False).reset_index().head(1)

  country    votes
0   India  2800164

## 6. Qual o nome do país que possui a maior quantidade de restaurantes que fazem entrega?

In [115]:
df1.groupby("country")["is_delivering_now"].nunique().sort_values(ascending=False).reset_index().head(1)

  country  is_delivering_now
0   India                  2

## 7. Qual o nome do país que possui a maior quantidade de restaurantes que aceitam reservas?

In [116]:
df1.groupby("country")["has_table_booking"].nunique().sort_values(ascending=False).reset_index().head(1)

     country  has_table_booking
0  Australia                  2

## 8. Qual o nome do país que possui, na média, a maior quantidade de avaliações registrada?

In [117]:
df1.groupby("country")["votes"].mean().idxmax()

'Indonesia'

## 9. Qual o nome do país que possui, na média, a maior nota média registrada?

In [118]:
df1.groupby("country")["aggregate_rating"].mean().idxmax()

'Indonesia'

## 10. Qual o nome do país que possui, na média, a menor nota média registrada?

In [119]:
df1.groupby("country")["aggregate_rating"].mean().idxmin()

'Brazil'

## 11. Qual a média de preço de um prato para dois por país?

In [17]:
df1.groupby("country")["average_cost_for_two"].mean().sort_values(ascending=False).astype(float).round(2).reset_index()

                 country  average_cost_for_two
0              Indonesia             303000.00
1              Australia             138959.78
2              Sri Lanka               2579.38
3            Phillipines               1227.82
4                  India                704.40
5           South Africa                339.23
6                  Qatar                174.00
7   United Arab Emirates                153.72
8              Singapore                141.44
9                 Brazil                138.81
10                Turkey                128.58
11           New Zealand                 62.15
12         United States                 55.03
13        United Kingdom                 43.51
14                Canada                 41.86

# Cidade

## 1. Qual o nome da cidade que possui mais restaurantes registrados?

In [121]:
df1.groupby("city")["restaurant"].nunique().idxmax()

'Abu Dhabi'

## 2. Qual o nome da cidade que possui mais restaurantes com nota média acima de 4?

In [122]:
df1[df1["aggregate_rating"] > 4]["city"].value_counts().idxmax()

'Bangalore'

## 3. Qual o nome da cidade que possui mais restaurantes com nota média abaixo de 2.5?

In [123]:
df1[df1["aggregate_rating"] < 2.5]["city"].value_counts().idxmax()

'Gangtok'

## 4. Qual o nome da cidade que possui o maior valor médio de um prato para dois?

In [124]:
df1.groupby("city")["average_cost_for_two"].nunique().idxmax()

'Dubai'

## 5. Qual o nome da cidade que possui a maior quantidade de tipos de culinária distintas?

In [125]:
df1.groupby("city")["cuisines"].nunique().idxmax()

'Birmingham'

## 6. Qual o nome da cidade que possui a maior quantidade de restaurantes que fazem reservas?

In [126]:
df1.groupby("city")["has_table_booking"].nunique().idxmax()

'Abu Dhabi'

## 7. Qual o nome da cidade que possui a maior quantidade de restaurantes que fazem entregas?

In [127]:
df1.groupby("city")["is_delivering_now"].nunique().idxmax()

'Abu Dhabi'

## 8. Qual o nome da cidade que possui a maior quantidade de restaurantes que aceitam pedidos online?

In [128]:
df1.groupby("city")["has_online_delivery"].nunique().reset_index()

                city  has_online_delivery
0          Abu Dhabi                    2
1           Adelaide                    1
2               Agra                    2
3          Ahmedabad                    2
4          Allahabad                    2
..               ...                  ...
120    Washington DC                    1
121       Wellington                    1
122  Wellington City                    1
123         Zirakpur                    1
124         İstanbul                    1

[125 rows x 2 columns]

# Restaurantes

## 1. Qual o nome do restaurante que possui a maior quantidade de avaliações?

In [129]:
df1.groupby("restaurant_name")["votes"].nunique().idxmax()

"Domino's Pizza"

## 2. Qual o nome do restaurante com a maior nota média?

In [130]:
df1.groupby("restaurant_name")["aggregate_rating"].mean().idxmax()

'5 Napkin Burger'

## 3. Qual o nome do restaurante que possui o maior valor de um prato para duas pessoas?

In [131]:
df1.groupby("restaurant_name")["average_cost_for_two"].nunique().idxmax()

'The Chocolate Room'

## 4. Qual o nome do restaurante de tipo de culinária brasileira que possui a menor média de avaliação?

In [133]:
df1[df1["cuisines"].str.contains("Brazilian")].groupby("restaurant_name")["aggregate_rating"].mean().idxmin()

'Bar do Luiz Fernandes'

## 5. Qual o nome do restaurante de tipo de culinária brasileira, e que é do Brasil, que possui a maior média de avaliação?

In [134]:
df1[(df1["cuisines"].str.contains("Brazilian")) & (df1["country"] == "Brazil")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

'Braseiro da Gávea'

## 6. Os restaurantes que aceitam pedido online são também, na média, os restaurantes que mais possuem avaliações registradas?

In [135]:
df1.groupby("has_online_delivery")["votes"].mean()[1] > df1.groupby("has_online_delivery")["votes"].mean()[0]

True

## 7. Os restaurantes que fazem reservas são também, na média, os restaurantes que possuem o maior valor médio de um prato para duas pessoas?

In [137]:
df1.groupby("has_table_booking")["average_cost_for_two"].mean()[1] > df1.groupby("has_table_booking")["average_cost_for_two"].mean()[0]

True

## 8. Os restaurantes do tipo de culinária japonesa dos Estados Unidos da América possuem um valor médio de prato para duas pessoas maior que as churrascarias americanas (BBQ)?

In [139]:
df1[df1["cuisines"].str.contains("Japanese") & (df1["country"] == "United States of America")]["average_cost_for_two"].mean() > df1[df1["cuisines"].str.contains("BBQ") & (df1["country"] == "United States of America")]["average_cost_for_two"].mean()

False

# Tipos de Culinária

## 1. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a maior média de avaliação?

In [140]:
df1[df1["cuisines"].str.contains("Italian")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

"Andre's Cucina & Polenta Bar"

## 2. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a menor média de avaliação?

In [141]:
df1[df1["cuisines"].str.contains("Italian")].nsmallest(1, "aggregate_rating")["restaurant_name"].values[0]

'Avenida Paulista'

## 3. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a maior média de avaliação?

In [142]:
df1[df1["cuisines"].str.contains("American")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

'Brick Store Pub'

## 4. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a menor média de avaliação?

In [143]:
df1[df1["cuisines"].str.contains("American")].nsmallest(1, "aggregate_rating")["restaurant_name"].values[0]

'Alston Bar & Beef'

## 5. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a maior média de avaliação?

In [144]:
df1[df1["cuisines"].str.contains("Arabian")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

'Mandi@36'

## 6. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a menor média de avaliação?

In [145]:
df1[df1["cuisines"].str.contains("Arabian")].nsmallest(1, "aggregate_rating")["restaurant_name"].values[0]

'Raful'

## 7. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a maior média de avaliação?

In [146]:
df1[df1["cuisines"].str.contains("Japanese")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

'Mendokoro Ramenba'

## 8. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a menor média de avaliação?

In [147]:
df1[df1["cuisines"].str.contains("Japanese")].nsmallest(1, "aggregate_rating")["restaurant_name"].values[0]

'Banzai Sushi'

## 9. Dos restaurantes que possuem o tipo de culinária caseira, qual o nome do restaurante com a maior média de avaliação?

In [148]:
df1[df1["cuisines"].str.contains("Home-made")].nlargest(1, "aggregate_rating")["restaurant_name"].values[0]

'Kanaat Lokantası'

## 10. Dos restaurantes que possuem o tipo de culinária caseira, qual o nome do restaurante com a menor média de avaliação?

In [149]:
df1[df1["cuisines"].str.contains("Home-made")].nsmallest(1, "aggregate_rating")["restaurant_name"].values[0]

'GurMekan Restaurant'

## 11. Qual o tipo de culinária que possui o maior valor médio de um prato para duas pessoas?

In [150]:
df1.groupby("cuisines")["average_cost_for_two"].mean().idxmax()

'Modern Australian'

## 12. Qual o tipo de culinária que possui a maior nota média?

In [151]:
df1.groupby("cuisines")["aggregate_rating"].mean().idxmax()

'Others'

## 13. Qual o tipo de culinária que possui mais restaurantes que aceitam pedidos online e fazem entregas?

In [152]:
df1[(df1["has_online_delivery"] == True) & (df1["is_delivering_now"] == True)]["cuisines"].mode().iloc[0]

'North Indian'